import {useEffect,useRef,useState} from 'react'
type Job={job_id:string;filename:string;status:string;progress:string;error:string|null;input_type:string;output_format:string;reversible:boolean;warnings:string[];revision:number;reviewed_pages:number[];page_count:number;finding_count:number;verification_passed:boolean;strategy:string}
type Finding={id:number;type:string;value:string;source:string;page:number;boxes:number[][];keep:boolean;manual:boolean;block_id:string}
type Page={id:number;kind:string;blocks:string[];uncertain:number[][];width:number;height:number}
type Block={id:string;text:string;label:string}
type Review={pages:Page[];findings:Finding[];blocks:Block[];revision:number;reviewed_pages:number[]}
type Cap={formats:Record<string,string[]>;model:{ready:boolean;model:string};ocr_ready:boolean}
type Region={page:number;box:number[]}
const labels:Record<string,string>={PERSON:'姓名',PHONE_CN:'手机号',EMAIL:'邮箱',ID_CN:'身份证',BANK_ACCOUNT:'银行账号',ADDRESS:'地址',ORG:'组织',CUSTOMER:'客户',PROJECT_CODE:'项目代号',SECRET:'密钥/密码',CUSTOM_TERM:'自定义',IP_ADDRESS:'IP 地址',PASSPORT:'护照'}
const statuses:Record<string,string>={queued:'排队中',extracting:'解析文件',detecting:'识别中',needs_review:'待复核',queued_export:'等待导出',redacting:'生成中',verifying:'检查中',completed:'已完成',failed:'处理失败',interrupted:'已中断',cancelled:'已取消'}
const active=new Set(['queued','extracting','detecting','queued_export','redacting','verifying'])
let csrf=''
let bootstrap:Promise<boolean>|undefined
async function api(path:string,options:RequestInit={}){const response=await fetch('/api'+path,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),'X-RD-CSRF':csrf,...options.headers}});if(!response.ok){const data=await response.json().catch(()=>({detail:'请求失败'}));throw Error(typeof data.detail==='string'?data.detail:'输入内容不正确')}return response}
async function json(path:string,options:RequestInit={}){return (await api(path,options)).json()}
function connect(){if(!bootstrap)bootstrap=(async()=>{const fragment=new URLSearchParams(location.hash.slice(1));const code=fragment.get('pair');if(code){history.replaceState(null,'',location.pathname);const result=await json('/pair',{method:'POST',body:JSON.stringify({code})});csrf=result.csrf;return true}const result=await json('/session');csrf=result.csrf||'';return result.authenticated})();return bootstrap}
function Icon({name}:{name:string}){return <span className="icon" aria-hidden="true">{({shield:'◈',file:'▤',plus:'＋',arrow:'↗',check:'✓',lock:'▣',restore:'↶',close:'×'} as Record<string,string>)[name]||name}</span>}

export function App(){
 const[connected,setConnected]=useState(false),[tab,setTab]=useState('workspace'),[jobs,setJobs]=useState<Job[]>([]),[cap,setCap]=useState<Cap|null>(null),[selected,setSelected]=useState<string|null>(null),[review,setReview]=useState<Review|null>(null)
 const[files,setFiles]=useState<File[]>([]),[strategy,setStrategy]=useState('model'),[output,setOutput]=useState('auto'),[reversible,setReversible]=useState(true),[business,setBusiness]=useState(false),[terms,setTerms]=useState(''),[allow,setAllow]=useState('')
 const[page,setPage]=useState(0),[keep,setKeep]=useState<number[]>([]),[confirmed,setConfirmed]=useState<number[]>([]),[regions,setRegions]=useState<Region[]>([]),[extra,setExtra]=useState(''),[password,setPassword]=useState(''),[password2,setPassword2]=useState('')
 const[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false),[drawing,setDrawing]=useState(false),[drag,setDrag]=useState<number[]|null>(null),[search,setSearch]=useState('')
 const[recoverFile,setRecoverFile]=useState<File|null>(null),[recoverVault,setRecoverVault]=useState<File|null>(null),[recoverPassword,setRecoverPassword]=useState('')
 const loaded=useRef(''),lastSelected=useRef<string|null>(null)
 const job=jobs.find(j=>j.job_id===selected), current=review?.pages[page]
 const ext=files[0]?.name.split('.').pop()?.toLowerCase()||''
 const pageFindings=(review?.findings||[]).filter(f=>!f.manual&&(f.page===page||current?.blocks.includes(f.block_id))&&(!search||f.value.includes(search)||(labels[f.type]||f.type).includes(search)))
 const refresh=async()=>{setJobs(await json('/jobs'))}
 const loadReview=async(id:string)=>{const r:Review=await json(`/jobs/${id}/review`);setReview(r);setKeep(r.findings.filter(f=>f.keep).map(f=>f.id));setConfirmed(r.reviewed_pages);setRegions(r.findings.filter(f=>f.manual).flatMap(f=>f.boxes.map(box=>({page:f.page,box}))));setDirty(false);setExtra('');return r}
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await fn()}catch(error){setNotice((error as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{let alive=true;connect().then(ok=>{if(alive)setConnected(ok)}).catch(e=>{if(alive)setNotice(e.message)});return()=>{alive=false}},[])
 useEffect(()=>{if(!connected)return;let alive=true;const update=async()=>{try{const[j,c]=await Promise.all([json('/jobs'),json('/capabilities')]);if(alive){setJobs(j);setCap(c)}}catch(e){if(alive)setNotice((e as Error).message)}};void update();const timer=setInterval(update,3000);return()=>{alive=false;clearInterval(timer)}},[connected])
 useEffect(()=>{if(!selected){setReview(null);return}if(lastSelected.current!==selected){lastSelected.current=selected;loaded.current='';setReview(null);setPage(0);setDirty(false)}if(job&&['needs_review','completed'].includes(job.status)){const key=selected+':'+job.revision;if(loaded.current!==key){loaded.current=key;void loadReview(selected).catch(e=>setNotice(e.message))}}},[selected,job?.revision,job?.status])
 const submit=()=>act(async()=>{if(!files.length)throw Error('请选择文件');let first='';for(const file of files){const data=new FormData();data.append('input_file',file);data.append('strategy',strategy);data.append('output_format',files.length===1?output:'auto');data.append('reversible',String(reversible));data.append('business',String(business));data.append('terms',terms);data.append('allow',allow);const created:Job=await json('/jobs',{method:'POST',body:data});if(!first)first=created.job_id}await refresh();setSelected(first);setTab('workspace');setFiles([]);setNotice('文件已加入本地处理队列。')})
 const save=async()=>{if(!job||!review)throw Error('请选择任务');const result:Job=await json(`/jobs/${job.job_id}/review`,{method:'POST',body:JSON.stringify({revision:review.revision,keep_ids:keep,confirmed_pages:confirmed,manual:regions,extra_terms:extra.split('\n').map(t=>t.trim()).filter(Boolean)})});loaded.current=job.job_id+':'+result.revision;await loadReview(job.job_id);await refresh();return result}
 const exportFile=()=>act(async()=>{if(!job) return;if(confirmed.length!==review?.pages.length)throw Error('请逐页检查并确认，包括没有候选项的页面。');if(job.reversible&&(password.length<10||password!==password2))throw Error('请设置至少 10 位的恢复密码，并确保两次输入一致。');const saved=await save();if(saved.reviewed_pages.length!==saved.page_count)throw Error('补充敏感词已加入，请重新逐页确认。');await json(`/jobs/${job.job_id}/exports`,{method:'POST',body:JSON.stringify({revision:saved.revision,password})});setPassword('');setPassword2('');await refresh()})
 const position=(event:React.PointerEvent<SVGSVGElement>)=>{const rect=event.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width)),Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height))]}
 const addRegion=(event:React.PointerEvent<SVGSVGElement>)=>{if(!drawing||!drag)return;const [x,y]=position(event);const box=[Math.min(drag[0],x),Math.min(drag[1],y),Math.max(drag[0],x),Math.max(drag[1],y)];if(box[2]-box[0]>.002&&box[3]-box[1]>.002){setRegions(prev=>[...prev,{page,box}]);setDirty(true)}setDrag(null)}
 const restore=()=>act(async()=>{if(!recoverFile||!recoverVault)throw Error('请选择脱敏文件和对应恢复包');const data=new FormData();data.append('redacted',recoverFile);data.append('recovery',recoverVault);data.append('password',recoverPassword);const response=await api('/restore',{method:'POST',body:data});const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=response.headers.get('Content-Disposition')?.match(/filename="([^"]+)"/)?.[1]||'restored';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setRecoverPassword('');setNotice('原始文件已恢复并下载，内容已通过摘要校验。')})
 if(!connected)return <main className="pairing"><div className="brand-mark"><Icon name="shield"/></div><h1>本地文件脱敏</h1><p>请双击项目中的「启动本地脱敏.cmd」打开应用。</p><p>配对入口仅对本次启动有效，所有文件在本机处理。</p>{notice&&<div className="alert">{notice}</div>}</main>
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark"><Icon name="shield"/></div><div>本地文件脱敏<small>LOCAL REDACTOR</small></div></div><div className="nav-label">工作空间</div><button className={'nav-item '+(tab==='workspace'?'chosen':'')} onClick={()=>setTab('workspace')}><Icon name="file"/>文件脱敏<span>{jobs.length}</span></button><button className={'nav-item '+(tab==='restore'?'chosen':'')} onClick={()=>setTab('restore')}><Icon name="restore"/>反脱敏恢复</button><div className="nav-label recent-label">最近任务 <button aria-label="新建任务" onClick={()=>{setSelected(null);setTab('workspace')}}>＋</button></div><div className="job-list">{jobs.length===0?<p className="muted empty-side">还没有任务<br/>导入文件即可开始</p>:jobs.map(j=><button key={j.job_id} className={'job-item '+(selected===j.job_id?'selected':'')} onClick={()=>{setSelected(j.job_id);setTab('workspace')}}><span className="file-icon">{j.input_type.toUpperCase()}</span><span className="job-info"><strong>{j.filename}</strong><small><i className={'dot '+(j.status==='completed'?'green':'')}/>{statuses[j.status]||j.status}</small></span></button>)}</div><div className="privacy-card"><Icon name="lock"/><strong>文件留在你的电脑</strong><p>本地识别 · 加密任务存储<br/>任务副本 24 小时后清理</p></div><div className="sidebar-foot">单机工作空间 <span>v2.0</span></div></aside>
  <main className="main"><header className="topbar"><div className="breadcrumb">工作空间 <span>/</span> {tab==='restore'?'恢复原文件':'文件脱敏'}</div><div className="local-badge"><i className="dot green"/>本机运行</div></header>
  <div className="main-content"><div className="page-heading"><div><div className="eyebrow">PRIVATE BY DESIGN</div><h1>{tab==='restore'?'恢复原始文件':job?'复核与导出':'让文件安全地分享'}</h1><p>{tab==='restore'?'使用脱敏文件、对应恢复包与密码，恢复完整原文件。':job?'检查候选信息和每一页内容，再生成新的脱敏文件。':'识别敏感信息，逐页确认，输出对应格式的脱敏文件。'}</p></div>{tab==='workspace'&&job&&<button className="secondary" onClick={()=>setSelected(null)}><Icon name="plus"/>新建任务</button>}</div>
  {notice&&<div role="alert" className="alert"><span>{notice}</span><button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}
  {tab==='restore'?<section className="panel recovery-panel"><div className="section-title"><span className="step">↶</span><div><h2>反脱敏恢复</h2><p>无需保留原任务，恢复包可以独立使用。</p></div></div><div className="recovery-fields"><label>脱敏文件<input type="file" onChange={e=>setRecoverFile(e.target.files?.[0]||null)}/></label><label>加密恢复包（.rdvault）<input type="file" accept=".rdvault" onChange={e=>setRecoverVault(e.target.files?.[0]||null)}/></label><label>恢复密码<input type="password" autoComplete="off" value={recoverPassword} onChange={e=>setRecoverPassword(e.target.value)} placeholder="输入导出时设置的密码"/></label></div><div className="info-note">恢复结果与原始文件字节一致。修改过的脱敏文件将无法通过匹配检查；不会把后续编辑合并回原文件。请单独保管恢复包和密码。</div><button onClick={restore} disabled={busy}>{busy?'正在校验与恢复…':'恢复并下载原文件'}<Icon name="arrow"/></button></section>:<>
   <div className="capabilities"><div><i className={'dot '+(cap?.model.ready?'green':'amber')}/><span>本地模型</span><strong>{cap?.model.ready?'Qwen3.5 · 9B':'等待模型就绪'}</strong></div><div><i className={'dot '+(cap?.ocr_ready?'green':'amber')}/><span>文字识别</span><strong>{cap?.ocr_ready?'PP-OCRv5':'OCR 未就绪'}</strong></div><div><Icon name="lock"/><span>反脱敏</span><strong>密码加密恢复包</strong></div></div>
   {!job?<><section className="panel"><div className="section-title"><span className="step">01</span><div><h2>导入文件</h2><p>支持批量导入，文件依次在本机处理。</p></div><span className="subtle-label">单文件 ≤100 MB</span></div><label className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setFiles(Array.from(e.dataTransfer.files).slice(0,20));setOutput('auto')}}><input aria-label="选择待脱敏文件" type="file" multiple accept=".pdf,.docx,.xlsx,.txt,.csv,.png,.jpg,.jpeg,.webp,.bmp" onChange={e=>{setFiles(Array.from(e.target.files||[]));setOutput('auto')}}/><span className="upload-icon"><Icon name="file"/></span><strong>{files.length?`已选择 ${files.length} 个文件`:'拖放文件到这里，或点击选择'}</strong><p>{files.length?files.map(f=>f.name).join('、'):'PDF、Word、Excel、文本、CSV 和常见图片'}</p><div className="format-tags">{['PDF','DOCX','XLSX','TXT / CSV','图片'].map(v=><span key={v}>{v}</span>)}</div></label></section>
   <section className="panel"><div className="section-title"><span className="step">02</span><div><h2>设置处理方式</h2><p>规则与模型提供候选，最终由你确认。</p></div></div><div className="settings-grid"><label>识别方式<select value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="model">规则 + 本地模型（推荐）</option><option value="rules_only">仅规则识别</option></select></label><label>输出格式<select value={output} onChange={e=>setOutput(e.target.value)} disabled={files.length!==1}><option value="auto">对应原格式（图片默认 PNG）</option>{cap?.formats[ext]?.map(v=><option key={v} value={v}>{v.toUpperCase()}</option>)}</select></label></div><div className="switch-row"><label><input type="checkbox" checked={reversible} onChange={e=>setReversible(e.target.checked)}/><span><strong>允许反脱敏</strong><small>导出时设置密码，另外生成加密恢复包；所有支持格式均可恢复。</small></span></label><label><input type="checkbox" checked={business} onChange={e=>setBusiness(e.target.checked)}/><span><strong>商务保密</strong><small>同时识别组织、客户、项目代号及 IP 地址。</small></span></label></div><details><summary>自定义敏感词与允许保留的词</summary><div className="settings-grid"><label>敏感词 · 每行一个<textarea rows={4} value={terms} onChange={e=>setTerms(e.target.value)} placeholder="客户名称、内部代号等"/></label><label>允许保留 · 完整匹配<textarea rows={4} value={allow} onChange={e=>setAllow(e.target.value)} placeholder="明确允许保留的完整词语"/></label></div></details><div className="info-note">Word 会重新排版，页眉页脚整理至正文；Excel 导出静态可编辑值。复杂图表、文本框或无缓存公式会明确提示先转换。PDF 输出保留可见页面，移除原文字层。</div><div className="panel-footer"><span>{strategy==='rules_only'?'仅规则模式不运行语义模型，需重点检查姓名和地址。':'文件处理仅连接本机服务，不发送至云端。'}</span><button onClick={submit} disabled={busy||!files.length||(strategy==='model'&&!cap?.model.ready)}>{busy?'正在导入…':'开始识别'}<Icon name="arrow"/></button></div></section></>:<>
   <section className="panel task-heading"><div className="task-name"><span className="file-icon large">{job.input_type.toUpperCase()}</span><div><h2>{job.filename}</h2><p>{job.input_type.toUpperCase()} → {job.output_format.toUpperCase()} <span>·</span> {job.page_count} 页/预览 <span>·</span> {job.finding_count} 项候选</p></div></div><span className={'status-pill '+(job.status==='completed'?'success':'')}>{statuses[job.status]}</span><div className="task-progress">{job.progress}{active.has(job.status)&&<span className="loader"/>}</div>{job.error&&<div className="error-box">{job.error}</div>}{job.warnings?.length>0&&<details><summary>处理说明与复核提醒（{job.warnings.length}）</summary>{job.warnings.map((w,i)=><p className="muted" key={i}>{w}</p>)}</details>}<div className="task-actions">{active.has(job.status)?<button className="secondary small" disabled={busy} onClick={()=>act(async()=>{await json(`/jobs/${job.job_id}/cancel`,{method:'POST'});await refresh()})}>取消处理</button>:<>{['failed','interrupted','cancelled'].includes(job.status)&&<button className="secondary small" onClick={()=>act(async()=>{await json(`/jobs/${job.job_id}/retry`,{method:'POST'});await refresh()})}>重新识别</button>}<button className="text-button" disabled={busy} onClick={()=>act(async()=>{await json(`/jobs/${job.job_id}`,{method:'DELETE'});setSelected(null);await refresh()})}>删除本机任务副本</button></>}</div></section>
   {review&&['needs_review','completed'].includes(job.status)&&<><div className="review-grid"><section className="panel preview-panel"><div className="preview-toolbar"><h2>逐页复核</h2><span>{page+1} / {review.pages.length}</span>{current?.kind==='image'&&<button className={'small '+(drawing?'':'secondary')} onClick={()=>setDrawing(!drawing)}>{drawing?'框选中':'手动框选'}</button>}</div><div className="preview-stage"><div className="image-container"><img alt={`第 ${page+1} 页原始预览`} src={`/api/jobs/${job.job_id}/pages/${page}`}/><svg viewBox="0 0 1000 1000" preserveAspectRatio="none" className={drawing?'drawing':''} onPointerDown={e=>{if(drawing){e.currentTarget.setPointerCapture(e.pointerId);const[x,y]=position(e);setDrag([x,y,x,y])}}} onPointerMove={e=>{if(drag){const[x,y]=position(e);setDrag([drag[0],drag[1],x,y])}}} onPointerUp={addRegion} onPointerCancel={()=>setDrag(null)}>{(review.findings||[]).filter(f=>f.page===page&&!f.manual&&!keep.includes(f.id)).flatMap(f=>f.boxes.map((b,i)=><rect key={f.id+'-'+i} x={b[0]*1000} y={b[1]*1000} width={(b[2]-b[0])*1000} height={(b[3]-b[1])*1000} className="candidate-box"/>))}{regions.filter(r=>r.page===page).map((r,i)=><rect key={'m'+i} x={r.box[0]*1000} y={r.box[1]*1000} width={(r.box[2]-r.box[0])*1000} height={(r.box[3]-r.box[1])*1000} className="manual-box"/>)}{current?.uncertain.map((b,i)=><rect key={'u'+i} x={b[0]*1000} y={b[1]*1000} width={(b[2]-b[0])*1000} height={(b[3]-b[1])*1000} className="uncertain-box"/>)}{drag&&<rect x={Math.min(drag[0],drag[2])*1000} y={Math.min(drag[1],drag[3])*1000} width={Math.abs(drag[2]-drag[0])*1000} height={Math.abs(drag[3]-drag[1])*1000} className="manual-box"/>}</svg></div></div><div className="page-controls"><button className="secondary small" disabled={page===0} onClick={()=>setPage(page-1)}>上一页</button><label><input type="checkbox" checked={confirmed.includes(page)} onChange={e=>{setConfirmed(prev=>e.target.checked?[...prev,page]:prev.filter(p=>p!==page));setDirty(true)}}/>已检查本页全部内容</label><button className="secondary small" disabled={page>=review.pages.length-1} onClick={()=>setPage(page+1)}>下一页</button></div><p className="preview-hint">红色为待遮除区域，紫色为手动区域，黄色为低清晰度区域。请检查签名、印章、人脸、二维码及未识别文字。</p>{regions.some(r=>r.page===page)&&<button className="text-button" onClick={()=>{setRegions(r=>r.filter(x=>x.page!==page));setDirty(true)}}>清除本页手动区域</button>}</section>
   <section className="panel findings-panel"><div className="preview-toolbar"><h2>本页候选 <span className="count">{pageFindings.length}</span></h2></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="筛选候选内容或类型"/><div className="findings-list">{pageFindings.length===0?<div className="no-findings"><Icon name="file"/><strong>本页未找到匹配候选</strong><p>仍需检查页面，可以补充敏感词或手动框选。</p></div>:pageFindings.map(f=><div className={'finding '+(keep.includes(f.id)?'kept':'')} key={f.id}><div><span className="entity-label">{labels[f.type]||f.type}</span><label><input type="checkbox" checked={keep.includes(f.id)} onChange={e=>{setKeep(p=>e.target.checked?[...p,f.id]:p.filter(id=>id!==f.id));setDirty(true)}}/>保留原文</label></div><p>{f.value}</p><small>{f.source}</small></div>)}</div><div className="extra-terms"><label>补充遗漏的敏感词<textarea value={extra} onChange={e=>{setExtra(e.target.value);setDirty(true)}} rows={2} placeholder="每行一个；保存后在全文匹配"/></label><button className="secondary small" disabled={busy} onClick={()=>act(async()=>{await save();setNotice('复核修改已保存。新增候选后需重新确认页面。')})}>保存复核修改{dirty?' *':''}</button></div></section></div>
   {job.status==='completed'&&!dirty?<section className="panel export-success"><div className="success-icon">✓</div><div><h2>脱敏文件已生成</h2><p>结构与选中内容检查通过。请将恢复包和密码与对外文件分开保管。</p><div className="download-links"><a className="button" href={`/api/jobs/${job.job_id}/download/redacted`}>下载脱敏文件 .{job.output_format}</a>{job.reversible&&<a className="button secondary" href={`/api/jobs/${job.job_id}/download/vault`}>下载加密恢复包</a>}<a className="report-link" href={`/api/jobs/${job.job_id}/download/report`}>处理报告 ↗</a></div></div></section>:<section className="panel export-panel"><div><h2>生成脱敏文件</h2><p>已确认 {confirmed.length} / {review.pages.length} 页。所有页面确认后可导出。</p></div>{job.reversible&&<div className="password-fields"><label>设置恢复密码<input type="password" autoComplete="new-password" placeholder="至少 10 个字符" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>再次输入密码<input type="password" autoComplete="new-password" value={password2} onChange={e=>setPassword2(e.target.value)}/></label></div>}<button disabled={busy||confirmed.length!==review.pages.length} onClick={exportFile}>生成脱敏文件<Icon name="arrow"/></button></section>}</>}
   </>}
  </>}
  <footer className="main-footer">本地处理 · 人工复核 · 可验证导出 <span>自动识别不代表零漏检，请检查后再分享。</span></footer></div></main></div>
}
